name: CI + Deploy Dev

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Databricks CLI
        run: |
          pip install databricks-cli
          pip install databricks-bundles
      - name: Validar bundle (Dev)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle validate --bundle-file ./databricks_bundle/dev/databricks.yml

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Databricks CLI
        run: |
          pip install databricks-cli
          pip install databricks-bundles
      - name: Deploy no Dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle deploy --bundle-file ./databricks_bundle/dev/databricks.yml --target dev