name: CI + Deploy Dev

on:
  pull_request:
    branches: [ "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Databricks CLI nova
        run: |
          curl -L https://github.com/databricks/cli/releases/latest/download/databricks_linux_amd64 -o databricks
          chmod +x databricks
          sudo mv databricks /usr/local/bin/
      - name: Validar bundle (Dev)
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle validate --bundle-file ./mentoria/databricks.yml

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      - name: Instalar Databricks CLI nova
        run: |
          curl -L https://github.com/databricks/cli/releases/latest/download/databricks_linux_amd64 -o databricks
          chmod +x databricks
          sudo mv databricks /usr/local/bin/
      - name: Deploy no Dev
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: databricks bundle deploy --bundle-file ./mentoria/databricks.yml --target dev
